spring.application.name=mail
spring.thymeleaf.prefix = classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.hiddenmethod.filter.enabled=true
spring.main.log-startup-info=true
server.port=8083

# application.properties

server.servlet.context-path=/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rahuldivedi221@gmail.com
spring.mail.password=epqgsbjaudqsauir
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Logging
logging.level.com.email.demo=DEBUG
logging.level.org.springframework.mail=DEBUG